### PR TITLE
Bug fixing for suggest command

### LINKED ISSUE #108: Bug fixing for suggest command

### LINKED ISSUE #117: [PE-D][Tester D] Inconsistent constraints on parameters
# Description

The user’s profile does not have a limit on age, which is inconsistent with the upper bound defined for height and weight. If there are upper bounds for heights and weights, then there should be one for age.

## Steps to reproduce bug

Run the following command

```
setup g/f w/50 h/165 i/48 a/9999
```

## Expected behaviour

An error should be returned to the user, indicating that the age cannot be too large (similar to height and weight)

## Actual behaviour

A user profile is created for a 9999-year-old female who is 50kg and 165cm, with an ideal weight of 48kg.

-------------
Labels: `severity.Low` `type.FeatureFlaw`
original: marcuspang/ped#2

### LINKED ISSUE #138: [PE-D][Tester A] Setup command - User profile Input validation
Hi! Did some light testing of the setup command and seems like it's working as intended. However, perhaps some improvements to the input validation could be made to make it more accurate.

This is the profile of a person unlikely to exist that I've managed to set-up. It's a nitpick but perhaps it would be important towards handling errors in user inputs!

Perhaps, for the following fields, some changes could be made like:
- Height: Could be allowed for more extreme cases (e.g. beyond 220cm)
- Weight: Similar to height (https://en.wikipedia.org/wiki/List_of_heaviest_people - just to nitpick!)
- Age: Seems implausible that a user would be 10000 years old

-------------
Labels: `type.FunctionalityBug` `severity.Low`
original: Ssatu/ped#5

### PR DESCRIPTION
**Pull request by nicolelim02**
- Change the `age`, `weight` and `height` limit

Closes #108, closes #117, closes #138

### CODE REVIEW

File: src/main/java/seedu/nutrigoals/model/user/Age.java [hunk 1]
```diff
@@ -7,9 +7,11 @@
  * Represents the user's age
  */
 public class Age {
-    public static final String VALIDATION_REGEX = "^[1-9]\\d*$";
-    public static final String MESSAGE_CONSTRAINTS = "Age must be a number greater than 0";
+    public static final String VALIDATION_REGEX = "\\d+";
+    public static final String MESSAGE_CONSTRAINTS = "Age must take on a positive integer than is not too large.";
```
Comment (ruiqi7) [inline src/main/java/seedu/nutrigoals/model/user/Age.java]: Would this error message be too vague to the user? Especially since there is now also a lower bound restriction on the age? Could consider explicitly stating the upper and lower bounds on the value !

**Review by ruiqi7 — APPROVED** [review]
Tested and works, just left a comment on the error message 👍

File: src/main/java/seedu/nutrigoals/model/user/Age.java (hunk 1 above)
Comment (nicolelim02) [reply src/main/java/seedu/nutrigoals/model/user/Age.java]: Fixed!
