### PR TITLE
Fix bugs

### LINKED ISSUE #112: [PE-D][Tester E] UG should state non-negative integers for target
UG states that for target command calorie can "can only take on integer values" but it could maybe state non-negative integer values to provide clearer instructions.

-------------
Labels: `type.DocumentationBug` `severity.Low`
original: wadia82/ped#1

### LINKED ISSUE #115: [PE-D][Tester C] Handling of too large calorie exception is vague.
When calorie is too large, exception is thrown which  is good. But maybe can tell the user what is the maximum calorie of the food they can input so that they know the limit of the food calorie they can take.

A possible use case scenario for example:

A user only wants to input their caloric intake for the entire year (for exaggeration) so they take in say 100000000000000000000000 calorie for the year.

Exception is then thrown by the application as shown below.

A better way is to suggest to the user the max calorie intake they can input as the caloric content of the food.

-------------
Labels: `type.FeatureFlaw` `severity.Medium`
original: jwdavis0200/ped#3

### LINKED ISSUE #122: [PE-D][Tester B] Vague error message for `c/CALORIE` parameter
When a very large number such as `33333333333333333` is input into the `c/CALORIES` parameter, the error message does not specify what exactly "not too large" means. This constraint is also not elaborated in the user guide. Perhaps it may be better to make this clearer to the user in either the UG or the app itself, because I had to reduce the number a few times before it accepted my input. I am not sure which bug this falls under, so I have tagged it as a feature flaw as failing to execute a command multiple times despite entering near valid inputs hinders the "fast-typing" requirement.

-------------
Labels: `type.FeatureFlaw` `severity.VeryLow`
original: izzahaj/ped#1

### LINKED ISSUE #136: [PE-D][Tester E] Locate has very restricted locations
May try adding more locations as inputs for locate to enhance user experience.

-------------
Labels: `severity.VeryLow` `type.FeatureFlaw`
original: wadia82/ped#7

### LINKED ISSUE #137: [PE-D][Tester E] UG does not state allowed locations for locate
UG could state the inputs allowed as locations for locate. 

-------------
Labels: `type.DocumentationBug` `severity.Medium`
original: wadia82/ped#8

### PR DESCRIPTION
**Pull request by TanPingZhi**
## This PR will close 6 issues

- [Fix Calorie's MESSAGE_CONSTRAINTS](https://github.com/AY2223S1-CS2103T-T17-2/tp/pull/146/commits/c7639a34a2f43788d2c1bef9050c7574f551ee83)

Closes #115, closes #122
- [Add target restriction to UG](https://github.com/AY2223S1-CS2103T-T17-2/tp/pull/146/commits/b46a88e78c87bb9e0c939e0ff3f6f19dadfcf721)

Closes #112 
- [Add parameters to locate command in UG](https://github.com/AY2223S1-CS2103T-T17-2/tp/pull/146/commits/46f9c26050c3b9e80bd8185f6356195cc42c9cfc)

Closes #137, #140
- [Add more nus locations](https://github.com/AY2223S1-CS2103T-T17-2/tp/pull/146/commits/34b855e8283aca51b7dc03a300943bcf93a71cf6)

Closes #136

- [x] Add UML for locategym

### CODE REVIEW

File: src/main/java/seedu/nutrigoals/model/Calorie.java [hunk 1]
```diff
@@ -8,7 +8,7 @@
 public class Calorie {
     public static final String VALIDATION_REGEX = "\\d+";
     public static final String MESSAGE_CONSTRAINTS =
-        "Calorie must take on a non negative number that is not too large.";
+        "Calorie must take on an integer in between 0 and 2,147,483,647 inclusively";
```
Comment (xav168) [inline src/main/java/seedu/nutrigoals/model/Calorie.java]: Not sure if we are allowed to change this

**Review by xav168 — CHANGES_REQUESTED** [review]

File: src/main/java/seedu/nutrigoals/logic/parser/ParserUtil.java [hunk 2]
```diff
@@ -126,6 +126,12 @@ public static Location parseLocation(String locationName) throws ParseException
         out.put("LT9", new Location("LT9", "1.2952456082872508, 103.77221840699619"));
         // https://goo.gl/maps/EEWy1fTuFcBkqxT97
         out.put("AS6", new Location("AS6", "1.2955038493756006, 103.77324977312634"));
+        // https://goo.gl/maps/JqvjteGB87DLP5eL7
+        out.put("IT", new Location("IT", "1.2975840550675737, 103.77251102348825"));
+        // https://goo.gl/maps/foRXfEUYG3v3QKDi8
+        out.put("TCOMS", new Location("TCOMS", "1.2935168791869454, 103.77690208272466"));
+        // https://goo.gl/maps/SMVTaR564Hoahr1B8
+        out.put("VENTUS", new Location("VENTUS", "1.295314453199568, 103.77019611100641"));
```
Comment (ruiqi7) [inline src/main/java/seedu/nutrigoals/logic/parser/ParserUtil.java]: Not sure if we can add these, but to address the feature flaw mentioned by the tester, could perhaps mention in the UG that more locations will be added in future releases~ (can refer to the food items list for the `find` command in the UG for an example)

File: src/main/java/seedu/nutrigoals/logic/commands/LocateGymCommand.java [hunk 3]
```diff
@@ -13,9 +13,10 @@
  */
 public class LocateGymCommand extends Command {
     public static final String COMMAND_WORD = "locate";
+    // Remember to update the User guide
     public static final String MESSAGE_USAGE = COMMAND_WORD
         + ": Finds the nearest gym to your stated location\n"
-        + "Parameters: COM2 | S13 | S17 | CLB | USC | LT1 | AS6\n"
+        + "Parameters: COM2 | S13 | S17 | CLB | UHC | LT1 | LT9 | AS6\n"
```
Comment (TanPingZhi) [inline src/main/java/seedu/nutrigoals/logic/commands/LocateGymCommand.java:19]: This is the current locations in master

File: docs/UserGuide.md [hunk 4]
```diff
@@ -293,10 +293,15 @@ Locates and ranks the nearest gyms to user's location in NUS.
 
 Format: `locate LOCATION`
 
+Parameters: COM2 | S13 | S17 | CLB | UHC | LT1 | LT9 | AS6
```
Comment (nicolelim02) [inline docs/UserGuide.md]: Is this supposed to be rendered as a table?

Screenshot 2022-11-01 at 3 54 06 PM

File: docs/UserGuide.md [hunk 5]
```diff
@@ -293,10 +293,15 @@ Locates and ranks the nearest gyms to user's location in NUS.
...
+
 Example:
 
 * `locate S17` returns a list of gyms sorted from nearest to furthest from S17.
 
+:fast_forward: **Future update:**<br>
+More nus locations will be added
```
Comment (nicolelim02) [inline docs/UserGuide.md]:
```suggestion
More nus locations will be added.
```

Perhaps it would be better if this command is added into the Command Summary section?

File: docs/DeveloperGuide.md [hunk 6]
```diff
@@ -403,6 +403,31 @@ The following activity diagram outlines what happens when a user executes the `s
...
 
+
+### Locate gym feature
+
+#### Implementation
+
+The locate gym mechanism is facilitated by `LocateGymCommand`, which extends `Command`. It overrides the
+following operation:
+
+* `LocateGymCommand#execute()`: Retrieves and displays the user's information.
```
Comment (nicolelim02) [inline docs/DeveloperGuide.md]: Is the description incorrect?

**Review by xav168 — APPROVED** [review]
